### PR TITLE
Update schemas submodule to latest

### PR DESCRIPTION
**Pull request by skenaja**
https://opencorporates.atlassian.net/browse/OCD-776

### CODE REVIEW

**Comment by bensymonds** [comment]
@skenaja I assume you've reviewed the changes in the schema and are happy nothing will break?

**Comment by skenaja** [comment]
The main change affecting company.json is the one we want https://github.com/openc/openc-schema/compare/898b5ae4bafb1d774884a7b84d3430213cf1d7e4...8e7f1fb6838883e0a2dc57b47d8a62cbf470aa7c#diff-7d605b906f2e585cfb72d226941600bf (relating to website as array)

No "includes/xxx.json" files used by company.json affected

I will check whether the change from "date-time" to "date" is breaking or not.

**Comment by thomasmarshall** [comment]
Here is the full comparison with latest version of `openc-schema`: https://github.com/openc/openc-schema/compare/898b5ae4bafb1d774884a7b84d3430213cf1d7e4...4da657b897b2b3ce36b660ef697c5f85d68fc5cf

**Comment by bensymonds** [comment]
@thomasmarshall Note the travis build failures. Did we try and update this dependency once before and see similar ones? I can't remember.

**Comment by skenaja** [comment]
@shyamperi has checked that change in retrieved_at from "date-time" to "date" is non-breaking for the external bots

**Comment by thomasmarshall** [comment]
As discussed, the required change here is for the `website` property of the company schema to allow an array. Given `openc_bot` only uses the company schema, and that none of the references/includes have changed in a breaking way, I think this is safe to update.

We need to discuss what to do about failing Travis builds.

**Comment by thomasmarshall** [comment]
I've fixed the travis build issues by updating bundler.

**Pull request merged**
