### PR TITLE
Add #get_raw_data and #save_raw_data utility methods

### PR DESCRIPTION
**Pull request by CountCulture**

### CODE REVIEW

**Comment by sebbacon** [comment]
Why a separate "format" argument? 

If we generalise to a document store model, then documents would just have ids, with optional metadata.

**Comment by CountCulture** [comment]
I guess for two reasons:
1) for clarity -- it's 'nice' to be able to see what type of file it is, plus if we were going to display as part of our audit trail (e.g. HTML in an i-frame) we probably need to now how to render it
2) in the case of Canada at least there's more than one format per uid (XML and HTML)

The format could however be incorporated in the identifier, I guess. Is that better. Will people remember?

**Comment by CountCulture** [comment]
Thinking about this further, I guess this is considered to be optional meta-data. @sebbacon would it be better to have an options hash, or maybe in the short term (as this is the only meta-data we know we want right now) just allow format to be optional?

**Comment by CountCulture** [comment]
@sebbacon Do you want me to change this?

**Comment by CountCulture** [comment]
@sebbacon Resolved this by making format to be optional

**Pull request merged**
