### PR TITLE
support stale_entry check when no underlying entry is available in

### PR DESCRIPTION
**Pull request by shyamperi**
database; ordered search results during update_stale

### CODE REVIEW

**Comment by CountCulture** [comment]
@shyamperi if you look at the commits here, I first handled the ordering issue, and added some specs to test the behaviour.
Then I handled the case where we want it to return true if there's no record. I figured out why the spec was passing when the behaviour hadn't been implemented, fixed the test, and added a test for the behaviour when there was no ocdata table (which was why the test erroneously passed).
Finally after making the commit, I realised that the conditional could be written more clearly, and changed that using a fixup. This will get squashed before I merge.
I left out the code related to multiple results, as a) this is different functionality unrelated to the problem b) uid is unique field in the database. If we think there could ever be more than one result per uid something is going screwy, and this isn't the place to be testing for such fundamental issues.
Hope this makes sense. HT to @bensymonds for helping me with git etiquette.

**Comment by shyamperi** [comment]
Thanks for explaining clearly. From next time I will try to follow the etiquette

**Comment by shyamperi** [comment]
👍ship it

**Comment by CountCulture** [comment]
NP. Now I've squashed the fixup by doing a `git rebase interactive master`

**Pull request merged**
